
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
  path('',views.index,name='index'),
  path('city',views.city,name='city'),
  path('driverinahmedabad',views.driverinahmedabad,name='driverinahmedabad'),
  path('driverinbengaluru',views.driverinbengaluru,name='driverinbengaluru'),
  path('abc',views.abc,name='abcl'),
    path('about',views.about,name='about'),
    path('blog.html',views.blog,name="blog"),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('business.html',views.business),
    path('businessaccount.html',views.businessaccount),
    path('captain.html',views.captain),
    path('chauffeur',views.chauffeur,name='chauffeur'),
    path('city/',views.city,name='city'),
    path('contact',views.contact,name='contact'),
    path('driver',views.driver,name='driver'),
    path('driverinagra',views.driverinagra,name='driverinagra'),
    path('driverinamritsar',views.driverinamritsar,name='driverinamritsar'),
    path('driverinayodhya',views.driverinayodhya,name='driverinayodhya'),
    path('driverinbhopal',views.driverinbhopal,name='driverinbhopal'),
    path('driverinchandigarh',views.driverinchandigarh,name='driverinchandigarh'),
    path('driverinchennai',views.driverinchennai,name='driverinchennai'),
    path('driverincoimbatore',views.driverincoimbatore,name='driverincoimbatore'),
    path('driverindehradun',views.driverindehradun,name='driverindehradun'),
    path('driverindelhi',views.driverindelhi,name='driverindelhi'),
    path('driveringoa',views.driveringoa,name='driveringoa'),
    path('driveringurugram',views.driveringurugram,name='driveringurugram'),
    path('driveringuwahati',views.driveringuwahati,name='driveringuwahati'),
    path('driverinharidwar',views.driverinharidwar,name='driverinharidwar'),
    path('driverinhyderabad',views.driverinhyderabad,name='driverinhyderabad'),
    path('driverinimphal',views.driverinimphal,name='driverinimphal'),
    path('driverinindore',views.driverinindore,name='driverinindore'),
    path('driverinjaipur',views.driverinjaipur,name='driverinjaipur'),
    path('driverinkanpur',views.driverinkanpur,name='driverinkanpur'),
    path('driverinkochi',views.driverinkochi,name='driverinkochi'),
    path('driverinkolkata',views.driverinkolkata,name='driverinkolkata'),
    path('driverinlucknow',views.driverinlucknow,name='driverinlucknow'),
    path('driverinludhiyana',views.driverinludhiana,name='driverinludhiyana'),
    path('driverinmadurai',views.driverinmadurai,name='driverinmadurai'),
    path('driverinmumbai',views.driverinmumbai,name='driverinmumbai'),
    path('driverinmysuru',views.driverinmysuru,name='driverinmysuru'),
    path('driverinnagpur',views.driverinnagpur,name='driverinnagpur'),
    path('driverinnashik',views.driverinnashik,name='driverinnashik'),
    path('driverinnoida',views.driverinnoida,name='driverinnoida'),
    path('driverinpatna',views.driverinpatna,name='driverinpatna'),
    path('driverinpune',views.driverinpune,name='driverinpune'),
    path('driverinraipur',views.driverinraipur,name='driverinraipur'),
    path('driverinrajkot',views.driverinrajkot,name='driverinrajkot'),
    path('driverinranchi',views.driverinranchi,name='driverinranchi'),
    path('driverinshimla',views.driverinshimla,name='driverinshimla'),
    path('driverinsiliguri',views.driverinsiliguri,name='driverinsiliguri'),
    path('driverinsurat',views.driverinsurat,name='driverinsurat'),
    path('driverinudaipur',views.driverinudaipur,name='driverinudaipur'),
    path('driverinvadodara',views.driverinvadodara,name='driverinvadodara'),
    path('driverinvaranasi',views.driverinvaranasi,name='driverinvaranasi'),
    path('driverinvisakhapatnam',views.driverinvisakhapatnam,name='driverinvisakhapatnam'),
    path('drivewithus',views.drivewithus,name='drivewithus'),
    path('help',views.help,name='help'),
    path('home',views.home,name='home'),
    path('howitworks',views.howitworks,name='howitworks'),
    path('offers',views.offers,name='offers'),
    path('privacy',views.privacy,name='privacy'),
    path('refund/',views.refund,name='refund'),
    path('services',views.services,name='services'),
    path('terms',views.terms,name='terms'),
    path('velet',views.velet,name='velet'),
    
    path('filter_drivers_state/', views.filter_drivers_state, name='filter_drivers_state'),
    path('filter_drivers_district/', views.filter_drivers_district, name='filter_drivers_district'),
    path('filter_drivers_subdistrict/', views.filter_drivers_subdistrict, name='filter_drivers_subdistrict'),
    path('filter_drivers_driver_type/', views.filter_drivers_driver_type, name='filter_drivers_driver_type'),
    path('booking_page/<int:driver_id>/', views.booking_page, name='booking_page'),
    path('create_booking/',views.create_booking, name='create_booking'),
    # path('payment/success/', views.payment_success, name='payment_success'),
     path('payment/', views.process_payment, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
  path('<int:booking_id>/', views.booking_detail, name='booking_detail'),
    
    path('get_next_day_time/',views.get_next_day_time, name='get_next_day_time'),
    path('calculate-nights/',views.calculate_nights, name='calculate_nights'),
    
    path('generate-drivers/',views.generate_drivers, name='generate_drivers'),
    path('driver_details/<int:driver_id>/', views.driver_details, name='driver_details'),
    
    # ==============================For Driver+++++++++++++++++++++++++++++++++++++++
    path('drivewithus',views.drivewithus,name='drivewithus'),
  path('profile',views.profile,name='profile'),
  path('login_view',views.login_view,name='login_view'),
   path('customer_registration',views.customer_registration,name='customer_registration'),
  
  
  
  
  path('driverlogout/',views.driverlogout,name='driverlogout'),
  path('forget_password/', views.forget_password, name='forget_password'),
  path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
   path('profile/profile_edit', views.profile_edit, name='profile_edit'),
 
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)