# Generated by Django 4.1.7 on 2023-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(max_length=50)),
                ('ride_for', models.CharField(max_length=50)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_sub_type', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('duration_book', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=50)),
                ('city_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('duration', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('promo_amount', models.FloatField()),
                ('payble_amount', models.FloatField()),
                ('ap_code_final', models.CharField(max_length=50)),
                ('billing_phone', models.CharField(max_length=50)),
                ('billing_name', models.CharField(max_length=100)),
                ('billing_email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
