# Generated by Django 4.1.7 on 2023-04-06 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_driver',
            old_name='payble_amount',
            new_name='payable_amount',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='duration_book',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='month',
        ),
        migrations.RemoveField(
            model_name='booking_driver',
            name='time',
        ),
        migrations.AddField(
            model_name='booking_driver',
            name='drop_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking_driver',
            name='pickup_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking_driver',
            name='drop_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking_driver',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking_driver',
            name='pickup_location',
            field=models.CharField(max_length=50),
        ),
    ]
