# Generated by Django 4.1.7 on 2023-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_driver_ap_code_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_driver',
            name='drop_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_driver',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
