# Generated by Django 4.1.7 on 2023-04-13 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_booking_driver_oneway_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='district',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='subdistrict',
        ),
        migrations.AddField(
            model_name='driver',
            name='aadharno',
            field=models.BigIntegerField(default=1547419630145),
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(default='anand', max_length=300),
        ),
        migrations.AddField(
            model_name='driver',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='cpassword',
            field=models.CharField(default='KDIT21022', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_licence',
            field=models.ImageField(default=None, max_length=500, upload_to='RegLicence/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='KD@gmail.com', max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='fname',
            field=models.CharField(default='Krunal', max_length=70),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lname',
            field=models.CharField(default='Ninama', max_length=70),
        ),
        migrations.AddField(
            model_name='driver',
            name='mname',
            field=models.CharField(default='D', max_length=70),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='KDIT21022', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.IntegerField(default=1598526540),
        ),
        migrations.AddField(
            model_name='driver',
            name='selfie',
            field=models.ImageField(default=None, max_length=500, upload_to='RegSelfie'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vytpe',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='zipcode',
            field=models.IntegerField(default=388001),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.CharField(default='anand', max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
