# Generated by Django 4.1.7 on 2023-04-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_driver_city_driver_district_driver_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cpassword',
            field=models.CharField(default='KDIT21022', max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(default='KDIT21022', max_length=200),
        ),
    ]
