# Generated by Django 4.1.7 on 2023-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_driver_cpassword_alter_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.BigIntegerField(default=1598526540),
        ),
    ]
