# Generated by Django 4.1.7 on 2023-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_driver_oneway',
            name='drop_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking_driver_oneway',
            name='pickup_location',
            field=models.CharField(max_length=100),
        ),
    ]
