# Generated by Django 4.1.7 on 2023-04-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_booking_driver_oneway_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_driver_oneway',
            name='customer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AlterField(
            model_name='booking_driver_roundway',
            name='customer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
