# Generated by Django 4.1.7 on 2023-04-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_booking_driver_oneway_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
