# Generated by Django 4.1.7 on 2023-04-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(choices=[('oneway', 'One Way'), ('roundway', 'Round Way'), ('plan', 'Plan')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_oneway', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.booking_driver_oneway')),
                ('booking_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('booking_roundway', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.booking_driver_roundway')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
